GET http://localhost:3003/user/feed
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRkOTk5OWY2LTgzMTktNDk0OS1iNDNjLTMxM2JlODkxNDM5YSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MjkxMzg2NjQsImV4cCI6MTYyOTE0MjI2NH0.VG3tobu4zdEa7jfClSv-TNEjb19HBF9V9WBtEFdGZNc

###
GET http://localhost:3003/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk1OWVlOGYyLTY1NDItNDI4MS1iMGI0LWJjMWZmNjVlMDk1NiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYyOTEzNDI0NCwiZXhwIjoxNjI5MTM3ODQ0fQ.NPm-Z7kqL6UsPoo5_jOOopYwrw6wDAwrAWCtyhZ9tT0

###
GET http://localhost:3003/user/3b5bb57a-ee0b-4961-8142-a4ee6c89ace9
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk1OWVlOGYyLTY1NDItNDI4MS1iMGI0LWJjMWZmNjVlMDk1NiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYyOTEzNDI0NCwiZXhwIjoxNjI5MTM3ODQ0fQ.NPm-Z7kqL6UsPoo5_jOOopYwrw6wDAwrAWCtyhZ9tT0

###
GET http://localhost:3003/recipe/b85bdf54-e841-4c37-84a2-ccef4714c6b7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk1OWVlOGYyLTY1NDItNDI4MS1iMGI0LWJjMWZmNjVlMDk1NiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYyOTEzNDI0NCwiZXhwIjoxNjI5MTM3ODQ0fQ.NPm-Z7kqL6UsPoo5_jOOopYwrw6wDAwrAWCtyhZ9tT0

###
POST http://localhost:3003/signup
Content-Type: application/json

{
    "name": "NomeDoUsuario",
    "email": "emaildousuario@email.com",
    "password": "123456",
    "role": "normal"
}

###
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "emaildousuario@email.com",
    "password": "123456"
}

###
POST http://localhost:3003/recipe
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRkOTk5OWY2LTgzMTktNDk0OS1iNDNjLTMxM2JlODkxNDM5YSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MjkxMzYwMzEsImV4cCI6MTYyOTEzOTYzMX0.GTFPJWW9jFgQAWpBa15onw9zcbGj6ymadpkqhecGBuA

{
    "title": "Nova receita",
    "description": "descrição de nova receita"
}

###
POST http://localhost:3003/user/follow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRkOTk5OWY2LTgzMTktNDk0OS1iNDNjLTMxM2JlODkxNDM5YSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MjkxMzYwMzEsImV4cCI6MTYyOTEzOTYzMX0.GTFPJWW9jFgQAWpBa15onw9zcbGj6ymadpkqhecGBuA

{
    "userToFollowId": "3b5bb57a-ee0b-4961-8142-a4ee6c89ace9"
}

###
POST http://localhost:3003/user/unfollow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjczZGY5NTk2LWI1MmQtNGEwYi1hOWNmLTBjNDYyNjZiMjAyNCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYyODgwNTM0OSwiZXhwIjoxNjI4ODA4OTQ5fQ.rGOnujvZQG_6F8xhCet7X4Kxur6O2nXaDy6TYQNLAkY


{
    "userToUnfollowId": "1.2654665"
}

###
PUT http://localhost:3003/recipe/edit/90c161a8-a9d4-4e3a-a816-d2c452fc41d3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRkOTk5OWY2LTgzMTktNDk0OS1iNDNjLTMxM2JlODkxNDM5YSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MjkxMzYwMzEsImV4cCI6MTYyOTEzOTYzMX0.GTFPJWW9jFgQAWpBa15onw9zcbGj6ymadpkqhecGBuA

{
    "title": "novo título",
    "description": "nova descrição"
}

###
PUT http://localhost:3003/user/tempPass
Content-Type: application/json

{
    "email": "bruno.contateste.labenu@gmail.com"
}

###
DELETE http://localhost:3003/recipe/2,996515
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk1OWVlOGYyLTY1NDItNDI4MS1iMGI0LWJjMWZmNjVlMDk1NiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYyODg3MDMwNiwiZXhwIjoxNjI4ODczOTA2fQ.vUIReQiKp8gf0Y5iaJz2jvReULMhbWmpM9GO8m9RW_A

###
DELETE http://localhost:3003/user/959ee8f2-6542-4281-b0b4-bc1ff65e0956
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk1OWVlOGYyLTY1NDItNDI4MS1iMGI0LWJjMWZmNjVlMDk1NiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYyODg3MjMzMSwiZXhwIjoxNjI4ODc1OTMxfQ.psDFb5kkV5s0nfXxCHh29Ct4i9mrbjP0SrflvRg8gL8